### ISSUE TITLE
Database Design

### ISSUE THREAD

**Issue by trayharrington** [Blaque-Majick/02-29-pair-project#1]
- [ ] Define schema
- [ ] Create models for Schema

**Comment by sumeetjain** [comment]
Split these up into multiple issues please.

**Comment by Blaque-Majick** [comment]
- User Authentication
   -[ ] Create user's table
   -[ ] Signup Form

**Comment by Blaque-Majick** [comment]
- Login 
   - [ ] Login Form
   - [ ] Authenticate valid password
   - [ ] Logout Feature

**Comment by Blaque-Majick** [comment]
-Restrict access from various pages unless logged in

**Comment by Blaque-Majick** [comment]
- Search Function
   - [ ] Search form
   - [ ] Results page

**Comment by Blaque-Majick** [comment]
- Link Searches with Users

**Comment by Blaque-Majick** [comment]
- Store searches in Archive

**Comment by Blaque-Majick** [comment]
- Algorithm Construction
   - [ ] Define method for solution
   - [ ] Research regex 
   - [ ] Build algorithm
